spring:
  application:
    name: my-market
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/my_market
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/my_market
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

logging:
  level:
    root: INFO